"""
HW1F calibration must be fitted on the same term structure the simulation
and the swaption pricer use.

Before this change calibration.py priced the basket on a flat curve
P(0,t) = exp(-theta t) while /simulate reconstituted bonds off the
bootstrapped curve, so the (a, sigma) handed to the Monte Carlo were fitted
to a different world. These tests pin the analytic vol to the Jamshidian
closed form on a steep curve, and check the round trip: vols generated by
the model on a curve are recovered by calibrating on that curve.
"""
import math
from datetime import date

import pytest

from pricing.calibration import calibrate_hw1f, hw1f_swaption_vol_normal
from pricing.bermudan_swaption import price_european_swaption_hw1f_jamshidian
from pricing.curve import Curve, discount_fn_from_curve


# Steep, humped Nelson-Siegel-ish curve: 2.5% front, ~4.5% at 10Y.
def steep_disc_fn(t: float) -> float:
    if t <= 0:
        return 1.0
    r = 0.045 - 0.020 * math.exp(-t / 3.0) + 0.004 * (t / 10.0) * math.exp(-t / 10.0)
    return math.exp(-r * t)


def _forward_swap_rate(disc, Te, tenor, dt):
    n = int(round(tenor / dt))
    pay = [Te + (k + 1) * dt for k in range(n)]
    A = sum(dt * disc(t) for t in pay)
    return (disc(Te) - disc(pay[-1])) / A, A, pay


GRID = [(1.0, 5.0), (2.0, 5.0), (5.0, 5.0), (5.0, 10.0), (10.0, 5.0), (1.0, 1.0)]


class TestAnalyticVolOnCurve:

    @pytest.mark.parametrize("expiry_y,tenor_y", GRID)
    def test_matches_jamshidian_on_steep_curve(self, expiry_y, tenor_y):
        a, sigma = 0.05, 0.0030
        N, dt = 10_000_000.0, 1.0
        F, A, pay = _forward_swap_rate(steep_disc_fn, expiry_y, tenor_y, dt)

        sig_n = hw1f_swaption_vol_normal(a, sigma, 0.03, expiry_y, tenor_y, dt,
                                         discount_fn=steep_disc_fn) / 1e4
        bach = N * A * sig_n * math.sqrt(expiry_y) / math.sqrt(2 * math.pi)
        jam = price_european_swaption_hw1f_jamshidian(
            N, F, True, expiry_y, pay, [dt] * len(pay), a, sigma, steep_disc_fn,
        )["npv"]
        assert abs(bach - jam) / jam < 1e-3

    def test_curve_changes_the_answer(self):
        """A flat-theta vol and a curve vol are materially different numbers."""
        flat  = hw1f_swaption_vol_normal(0.05, 0.003, 0.03, 5.0, 5.0)
        curve = hw1f_swaption_vol_normal(0.05, 0.003, 0.03, 5.0, 5.0,
                                         discount_fn=steep_disc_fn)
        assert abs(flat - curve) > 0.25   # bp

    def test_none_discount_fn_is_flat_theta(self):
        theta = 0.037
        via_none = hw1f_swaption_vol_normal(0.04, 0.0025, theta, 3.0, 5.0)
        via_flat = hw1f_swaption_vol_normal(0.04, 0.0025, theta, 3.0, 5.0,
                                            discount_fn=lambda t: math.exp(-theta * t))
        assert via_none == pytest.approx(via_flat, rel=1e-12)

    def test_production_curve_wrapper(self):
        """discount_fn_from_curve on a real Curve object feeds the formula."""
        vd = date(2026, 9, 21)
        pillars = [(vd.replace(year=vd.year + k), steep_disc_fn(float(k)))
                   for k in (1, 2, 3, 5, 7, 10, 15, 20)]
        curve = Curve(vd, df_pillars=pillars)
        fn = discount_fn_from_curve(curve)
        assert fn(0.0) == 1.0
        assert fn(5.0) == pytest.approx(steep_disc_fn(5.0), rel=2e-3)  # 1-day rounding
        v = hw1f_swaption_vol_normal(0.05, 0.003, 0.03, 5.0, 5.0, discount_fn=fn)
        assert 10.0 < v < 100.0


class TestCalibrationRoundTrip:

    def _basket(self, a, sigma, disc):
        out = []
        for e, t in GRID:
            out.append({
                "expiry_y": e, "tenor_y": t,
                "vol_bp": hw1f_swaption_vol_normal(a, sigma, 0.03, e, t, discount_fn=disc),
                "ticker": f"{e}x{t}", "role": "test", "weight": 1.0,
            })
        return out

    def test_recovers_parameters_on_curve(self):
        a_true, sig_true = 0.04, 0.0032
        res = calibrate_hw1f(self._basket(a_true, sig_true, steep_disc_fn),
                             theta=0.03, a_init=0.02, sigma_bp_init=50.0,
                             discount_fn=steep_disc_fn)
        assert res["curve_source"] == "curve"
        assert res["fit_rmse_bp"] < 0.05
        assert res["a"] == pytest.approx(a_true, abs=2e-3)
        assert res["sigma_bp"] == pytest.approx(sig_true * 1e4, abs=0.3)

    def test_flat_calibration_of_curve_vols_is_biased(self):
        """Fitting curve-generated vols on the flat curve does NOT recover
        the parameters — the inconsistency this change removes."""
        a_true, sig_true = 0.04, 0.0032
        res = calibrate_hw1f(self._basket(a_true, sig_true, steep_disc_fn),
                             theta=0.03, a_init=0.02, sigma_bp_init=50.0)
        assert res["curve_source"] == "flat-theta"
        assert (abs(res["a"] - a_true) > 2e-3
                or abs(res["sigma_bp"] - sig_true * 1e4) > 0.3)
